### PR TITLE
2.3.0: adjust LICENSE and run tests after packaging

### PR DESCRIPTION
**Pull request by megies**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

closes conda-forge/pyshp-feedstock#18

 - building on top of #18 
 - adjusted LICENSE to match what upstream has
 - added a command to run tests after packaging, they dont take very long, so why not

### CODE REVIEW

**Comment by megies** [comment]
Nevermind, that test routine isn't working in the installed package right now, since it's outdated and relies on doctesting the README which isn't packaged right now.

There is a dedicated test file for pytest but it isn't packaged either right now, so probably just test importing the installed module like before.

**Comment by ocefpaf** [comment]
@megies we can use the GitHub tag to access all those files that are not in the PyPI tarball. More tests are always welcomed!

**Comment by megies** [comment]
Cool didn't know! Yeah, I like to run all the tests on the packages too.

**Comment by ocefpaf** [comment]
In the past we discouraged folks from running all the tests b/c we were CI limited. Since we moved to Azure that limitation was lifted and we are on the "run all the tests" team now :smile:

**Pull request merged**
